TOPDIR=../..
include $(TOPDIR)/pre.mk

CSOURCES=automata.c

INCLUDE=
LDLIBS+=$(shell $(TOPDIR)/gfxprim-config --libs --libs-widgets)

APPS=automata

include $(TOPDIR)/app.mk
include $(TOPDIR)/post.mk
